[ci] prereleases testing system base

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -2,11 +2,11 @@ name: cd
 on:
   pull_request:
   push:
-    branches: [master, cd-debug]
+    branches: [master, release-lock-testing]
+    paths: [semcore/*/CHANGELOG.md, pnpm-lock.yaml]
   workflow_dispatch:
 concurrency:
-  group: ${{ github.ref }}
-  cancel-in-progress: true
+  group: ${{ github.workflow }}-${{ github.ref }}
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -104,69 +104,70 @@ jobs:
         run: echo "success=true" >> $GITHUB_OUTPUT
     outputs:
       success: ${{ steps.final.outputs.success }}
-  test:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3.5.3
-      - name: Install Node.js
-        uses: actions/setup-node@v3.6.0
-        with:
-          node-version: 20
-      - uses: pnpm/action-setup@v2.2.4
-        name: Install pnpm
-        id: pnpm-install
-        with:
-          version: 7
-          run_install: false
-      - name: Get pnpm store directory
-        id: pnpm-cache
-        run: |
-          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
-      - uses: actions/cache@v3.3.1
-        name: Setup pnpm cache
-        with:
-          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
-          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
-      - name: Restore cached build
-        uses: actions/cache@v3.3.1
-        with:
-          path: |
-            semcore/*/lib
-            tools/*/lib
-            semcore/icon/**/*.js
-            semcore/icon/**/*.mjs
-            semcore/icon/**/*.d.ts
-            semcore/illustration/**/*.js
-            semcore/illustration/**/*.mjs
-            semcore/illustration/**/*.d.ts
-          key: build-${{ hashFiles('**/pnpm-lock.yaml', '**/CHANGELOG.md') }}-2
-      - name: Install restored dependencies
-        run: |
-          pnpm install --frozen-lockfile
-      - name: Test
-        id: test
-        run: pnpm coverage
-      - name: Save test results as artifacts
-        if: failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: test-results
-          path: test-results
-          retention-days: 3
-      - name: Upload coverage to Codecov
-        if: steps.test.conclusion == 'success'
-        uses: codecov/codecov-action@v3.1.4
-      - name: Setting success output
-        id: final
-        run: echo "success=true" >> $GITHUB_OUTPUT
-    outputs:
-      success: ${{ steps.final.outputs.success }}
+  # test:
+  #   runs-on: ubuntu-latest
+  #   needs: build
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v3.5.3
+  #     - name: Install Node.js
+  #       uses: actions/setup-node@v3.6.0
+  #       with:
+  #         node-version: 20
+  #     - uses: pnpm/action-setup@v2.2.4
+  #       name: Install pnpm
+  #       id: pnpm-install
+  #       with:
+  #         version: 7
+  #         run_install: false
+  #     - name: Get pnpm store directory
+  #       id: pnpm-cache
+  #       run: |
+  #         echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
+  #     - uses: actions/cache@v3.3.1
+  #       name: Setup pnpm cache
+  #       with:
+  #         path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
+  #         key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
+  #     - name: Restore cached build
+  #       uses: actions/cache@v3.3.1
+  #       with:
+  #         path: |
+  #           semcore/*/lib
+  #           tools/*/lib
+  #           semcore/icon/**/*.js
+  #           semcore/icon/**/*.mjs
+  #           semcore/icon/**/*.d.ts
+  #           semcore/illustration/**/*.js
+  #           semcore/illustration/**/*.mjs
+  #           semcore/illustration/**/*.d.ts
+  #         key: build-${{ hashFiles('**/pnpm-lock.yaml', '**/CHANGELOG.md') }}-2
+  #     - name: Install restored dependencies
+  #       run: |
+  #         pnpm install --frozen-lockfile
+  #     - name: Test
+  #       id: test
+  #       run: pnpm coverage
+  #     - name: Save test results as artifacts
+  #       if: failure()
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: test-results
+  #         path: test-results
+  #         retention-days: 3
+  #     - name: Upload coverage to Codecov
+  #       if: steps.test.conclusion == 'success'
+  #       uses: codecov/codecov-action@v3.1.4
+  #     - name: Setting success output
+  #       id: final
+  #       run: echo "success=true" >> $GITHUB_OUTPUT
+  #   outputs:
+  #     success: ${{ steps.final.outputs.success }}
   publish-components:
     runs-on: ubuntu-latest
-    needs: [lint, test, browser-test, vo-test, vo-filter]
-    if: always() && github.ref == 'refs/heads/master' && needs.lint.outputs.success == 'true' && needs.test.outputs.success == 'true' && needs.browser-test.outputs.success == 'true' && (needs.vo-test.outputs.success == 'true' || needs.vo-filter.outputs.run_vo == 'false')
+    # needs: [lint, test, browser-test, vo-test, vo-filter]
+    needs: [lint]
+    # if: always() && github.ref == 'refs/heads/release-lock-testing' && needs.lint.outputs.success == 'true' && needs.test.outputs.success == 'true' && needs.browser-test.outputs.success == 'true' && (needs.vo-test.outputs.success == 'true' || needs.vo-filter.outputs.run_vo == 'false')
     env:
       GITHUB_SECRET: ${{ secrets.BOT_ACCOUNT_GITHUB_TOKEN }}
       GCLOUD_SECRET: ${{ secrets.GCLOUD_SECRET }}
@@ -221,8 +222,8 @@ jobs:
           echo "strict-peer-dependencies=false" >> ".npmrc"
       - name: NPM auth check
         run: pnpm whoami
-      - name: Delivery
-        run: pnpm continuous-delivery
+      - name: Deliver prerelease
+        run: pnpm deliver-prerelease
   publish-website:
     runs-on: ubuntu-latest
     if: github.ref == 'refs/heads/master'
@@ -258,176 +259,150 @@ jobs:
           git checkout -b website/release
           git push --force --set-upstream origin website/release
           git push origin website/release --force
-  vo-filter:
-    runs-on: ubuntu-latest
-    needs: build
+  # vo-filter:
+  #   runs-on: ubuntu-latest
+  #   needs: build
 
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3.5.3
-      - name: Install Node.js
-        uses: actions/setup-node@v3.6.0
-        with:
-          node-version: 20
-      - uses: pnpm/action-setup@v2.2.4
-        name: Install pnpm
-        id: pnpm-install
-        with:
-          version: 7
-          run_install: false
-      - name: Get pnpm store directory
-        id: pnpm-cache
-        run: |
-          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
-      - uses: actions/cache@v3.3.1
-        name: Setup pnpm cache
-        with:
-          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
-          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
-      - name: Restore cached build
-        uses: actions/cache@v3.3.1
-        with:
-          path: |
-            semcore/*/lib
-            tools/*/lib
-            semcore/icon/**/*.js
-            semcore/icon/**/*.mjs
-            semcore/icon/**/*.d.ts
-            semcore/illustration/**/*.js
-            semcore/illustration/**/*.mjs
-            semcore/illustration/**/*.d.ts
-          key: build-${{ hashFiles('**/pnpm-lock.yaml', '**/CHANGELOG.md') }}-2
-      - name: Install restored dependencies
-        run: |
-          pnpm install --frozen-lockfile
-      - name: Generate VO tests hashes
-        run: |
-          pnpm tsm ./.ci/vo-tests-hash.ts
-      - name: Diff git and set output
-        id: final
-        run: |
-          if [[ $(git --no-pager diff .ci/.vo-test-hash.txt) ]]; then
-            echo "run_vo=true" >> $GITHUB_OUTPUT
-          else
-            echo "run_vo=false" >> $GITHUB_OUTPUT
-          fi
-    outputs:
-      run_vo: ${{ steps.final.outputs.run_vo }}
-  vo-test:
-    runs-on: macos-12
-    needs: vo-filter
-    if: needs.vo-filter.outputs.run_vo == 'true'
-    steps:
-      - uses: actions/checkout@v3.5.3
-        with:
-          token: ${{ secrets.BOT_ACCOUNT_GITHUB_TOKEN }}
-      - uses: pnpm/action-setup@v2.2.4
-        with:
-          version: 7
-          run_install: false
-      - name: Get pnpm store directory
-        id: pnpm-cache
-        run: |
-          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
-      - uses: actions/cache@v3.3.1
-        name: Restore pnpm cache
-        with:
-          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
-          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
-      - name: Restore cached build
-        uses: actions/cache@v3.3.1
-        with:
-          path: |
-            semcore/*/lib
-            tools/*/lib
-            semcore/icon/**/*.js
-            semcore/icon/**/*.mjs
-            semcore/icon/**/*.d.ts
-            semcore/illustration/**/*.js
-            semcore/illustration/**/*.mjs
-            semcore/illustration/**/*.d.ts
-          key: build-${{ hashFiles('**/pnpm-lock.yaml', '**/CHANGELOG.md') }}-2
-      - name: Install restored dependencies
-        run: |
-          pnpm install --frozen-lockfile
-      - name: Install Browser
-        run: npx playwright install webkit
-      - name: Enable VoiceOver Automation
-        uses: guidepup/setup-action@0.11.2
-      - name: Update VO tests hashes
-        run: |
-          pnpm tsm ./.ci/vo-tests-hash.ts
-      - name: Voice Over testing
-        uses: nick-fields/retry@v2.8.3
-        with:
-          timeout_minutes: 40
-          max_attempts: 3
-          command: pnpm run vo-test
-      - name: Github GPG Auth
-        uses: crazy-max/ghaction-import-gpg@v5.3.0
-        with:
-          gpg_private_key: ${{ secrets.BOT_ACCOUNT_GPG_PRIVATE_KEY }}
-          git_user_signingkey: true
-          git_commit_gpgsign: true
-          git_committer_name: semrush-ci-whale
-          git_committer_email: semrush-ci-whale@users.noreply.github.com
-      - name: Push changed a11y reports
-        run: git add . && git commit -m "[chore] a11y automatic check fixation" && git push || echo "nothing to commit"
-      - name: Setting success output
-        id: final
-        run: echo "success=true" >> $GITHUB_OUTPUT
-    outputs:
-      success: ${{ steps.final.outputs.success }}
-  browser-test:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - uses: actions/checkout@v3.5.3
-      - uses: pnpm/action-setup@v2.2.4
-        with:
-          version: 7
-          run_install: false
-      # - name: Get pnpm store directory
-      #   id: pnpm-cache
-      #   run: |
-      #     echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
-      # - uses: actions/cache@v3.3.1
-      #   name: Restore pnpm cache
-      #   with:
-      #     path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
-      #     key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
-      # - name: Restore cached build
-      #   uses: actions/cache@v3.3.1
-      #   with:
-      #     path: |
-      #       semcore/*/lib
-      #       tools/*/lib
-      #       semcore/icon/**/*.js
-      #       semcore/icon/**/*.mjs
-      #       semcore/icon/**/*.d.ts
-      #       semcore/illustration/**/*.js
-      #       semcore/illustration/**/*.mjs
-      #       semcore/illustration/**/*.d.ts
-      #     key: build-${{ hashFiles('**/pnpm-lock.yaml', '**/CHANGELOG.md') }}-2
-      # - name: Install restored dependencies
-      #   run: |
-      #     pnpm install --frozen-lockfile
-      # - name: Install Browser
-      #   run: npx playwright install --with-deps
-      - name: Browser testing
-        id: browser-testing
-        run: |
-          docker run --rm --network host -v $(pwd):/work -v /work/node_modules -v /work/.pnpm-store -v /work/.cache -w /work/ mcr.microsoft.com/playwright:v1.35.0-jammy bash -c "npm install --global pnpm@7 && pnpm install --ignore-scripts && pnpm build:icons && pnpm build:illustration && npx playwright install && CI=true pnpm playwright test --config playwright.browser.config.ts"
-      - name: Save test results as artifacts
-        if: failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: test-results
-          path: test-results
-          retention-days: 3
-      - name: Setting success output
-        if: steps.browser-testing.conclusion == 'success'
-        id: final
-        run: echo "success=true" >> $GITHUB_OUTPUT
-    outputs:
-      success: ${{ steps.final.outputs.success }}
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v3.5.3
+  #     - name: Install Node.js
+  #       uses: actions/setup-node@v3.6.0
+  #       with:
+  #         node-version: 20
+  #     - uses: pnpm/action-setup@v2.2.4
+  #       name: Install pnpm
+  #       id: pnpm-install
+  #       with:
+  #         version: 7
+  #         run_install: false
+  #     - name: Get pnpm store directory
+  #       id: pnpm-cache
+  #       run: |
+  #         echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
+  #     - uses: actions/cache@v3.3.1
+  #       name: Setup pnpm cache
+  #       with:
+  #         path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
+  #         key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
+  #     - name: Restore cached build
+  #       uses: actions/cache@v3.3.1
+  #       with:
+  #         path: |
+  #           semcore/*/lib
+  #           tools/*/lib
+  #           semcore/icon/**/*.js
+  #           semcore/icon/**/*.mjs
+  #           semcore/icon/**/*.d.ts
+  #           semcore/illustration/**/*.js
+  #           semcore/illustration/**/*.mjs
+  #           semcore/illustration/**/*.d.ts
+  #         key: build-${{ hashFiles('**/pnpm-lock.yaml', '**/CHANGELOG.md') }}-2
+  #     - name: Install restored dependencies
+  #       run: |
+  #         pnpm install --frozen-lockfile
+  #     - name: Generate VO tests hashes
+  #       run: |
+  #         pnpm tsm ./.ci/vo-tests-hash.ts
+  #     - name: Diff git and set output
+  #       id: final
+  #       run: |
+  #         if [[ $(git --no-pager diff .ci/.vo-test-hash.txt) ]]; then
+  #           echo "run_vo=true" >> $GITHUB_OUTPUT
+  #         else
+  #           echo "run_vo=false" >> $GITHUB_OUTPUT
+  #         fi
+  #   outputs:
+  #     run_vo: ${{ steps.final.outputs.run_vo }}
+  # vo-test:
+  #   runs-on: macos-12
+  #   needs: vo-filter
+  #   if: needs.vo-filter.outputs.run_vo == 'true'
+  #   steps:
+  #     - uses: actions/checkout@v3.5.3
+  #       with:
+  #         token: ${{ secrets.BOT_ACCOUNT_GITHUB_TOKEN }}
+  #     - uses: pnpm/action-setup@v2.2.4
+  #       with:
+  #         version: 7
+  #         run_install: false
+  #     - name: Get pnpm store directory
+  #       id: pnpm-cache
+  #       run: |
+  #         echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
+  #     - uses: actions/cache@v3.3.1
+  #       name: Restore pnpm cache
+  #       with:
+  #         path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
+  #         key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
+  #     - name: Restore cached build
+  #       uses: actions/cache@v3.3.1
+  #       with:
+  #         path: |
+  #           semcore/*/lib
+  #           tools/*/lib
+  #           semcore/icon/**/*.js
+  #           semcore/icon/**/*.mjs
+  #           semcore/icon/**/*.d.ts
+  #           semcore/illustration/**/*.js
+  #           semcore/illustration/**/*.mjs
+  #           semcore/illustration/**/*.d.ts
+  #         key: build-${{ hashFiles('**/pnpm-lock.yaml', '**/CHANGELOG.md') }}-2
+  #     - name: Install restored dependencies
+  #       run: |
+  #         pnpm install --frozen-lockfile
+  #     - name: Install Browser
+  #       run: npx playwright install webkit
+  #     - name: Enable VoiceOver Automation
+  #       uses: guidepup/setup-action@0.11.2
+  #     - name: Update VO tests hashes
+  #       run: |
+  #         pnpm tsm ./.ci/vo-tests-hash.ts
+  #     - name: Voice Over testing
+  #       uses: nick-fields/retry@v2.8.3
+  #       with:
+  #         timeout_minutes: 40
+  #         max_attempts: 3
+  #         command: pnpm run vo-test
+  #     - name: Github GPG Auth
+  #       uses: crazy-max/ghaction-import-gpg@v5.3.0
+  #       with:
+  #         gpg_private_key: ${{ secrets.BOT_ACCOUNT_GPG_PRIVATE_KEY }}
+  #         git_user_signingkey: true
+  #         git_commit_gpgsign: true
+  #         git_committer_name: semrush-ci-whale
+  #         git_committer_email: semrush-ci-whale@users.noreply.github.com
+  #     - name: Push changed a11y reports
+  #       run: git add . && git commit -m "[chore] a11y automatic check fixation" && git push || echo "nothing to commit"
+  #     - name: Setting success output
+  #       id: final
+  #       run: echo "success=true" >> $GITHUB_OUTPUT
+  #   outputs:
+  #     success: ${{ steps.final.outputs.success }}
+  # browser-test:
+  #   runs-on: ubuntu-latest
+  #   needs: build
+  #   steps:
+  #     - uses: actions/checkout@v3.5.3
+  #     - uses: pnpm/action-setup@v2.2.4
+  #       with:
+  #         version: 7
+  #         run_install: false
+
+  #     - name: Browser testing
+  #       id: browser-testing
+  #       run: |
+  #         docker run --rm --network host -v $(pwd):/work -v /work/node_modules -v /work/.pnpm-store -v /work/.cache -w /work/ mcr.microsoft.com/playwright:v1.35.0-jammy bash -c "npm install --global pnpm@7 && pnpm install --ignore-scripts && pnpm build:icons && pnpm build:illustration && npx playwright install && CI=true pnpm playwright test --config playwright.browser.config.ts"
+  #     - name: Save test results as artifacts
+  #       if: failure()
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: test-results
+  #         path: test-results
+  #         retention-days: 3
+  #     - name: Setting success output
+  #       if: steps.browser-testing.conclusion == 'success'
+  #       id: final
+  #       run: echo "success=true" >> $GITHUB_OUTPUT
+  #   outputs:
+  #     success: ${{ steps.final.outputs.success }}
